### ISSUE TITLE
What about the meaning of 'dynamic' in vtest_info before encrypt 

### ISSUE THREAD

**Issue by qyvlik** [chaincloud-dot-com/chaincloud-docs#1]
# What about the meaning of 'dynamic' in vtest_info before encrypt ?

> `vtest_info` encrypt with aes. decryption is {"outs":"1NbbvxBYxGGCBhaM8mow1HFWA7dB5yukmY,10000;1MCs9SZwLg9JvLo6pzvVBWtmSV1dakwyM1,10000","dynamic":0}, passwd is "20160721". The unit of value is in satoshi, the minimum is 10000 satoshi.

what about the meaning of 'dynamic'? Just a constant **ZERO**?

**Comment by qyvlik** [comment]
'dynamic' mean net fee, unit of value is satoshi.

**Comment by qyvlik** [comment]
dynamic： 是否需要动态手续费  0 不需要 1需要

**Comment by bithernet** [comment]
dynamic fee
